import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocationLayout({
  children,
  aqi,
  weather,
  temperature,
  wind,
}) {
  return (
    <div className="wrapper">
      {children}
      {weather}
      {aqi}
      {wind}
      {temperature}
    </div>
  );
}
