import Image from "next/image";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocationLayout({
  children,
  aqi,
  weather,
  temperature,
  wind,
}) {
  return (
    <div className="wrapper">
      <Image
        className="bg-img"
        src="/assets/images/background.png"
        height={1200}
        width={700}
        alt="background"
      />
      <div className="overlay"></div>
      <main className="!z-50 w-full">
        <div className="container">
          <div className="grid grid-cols-12 gap-y-8 py-16 lg:gap-8 2xl:gap-20 2xl:py-20">
            {children}
            {weather}
            {aqi}
            {wind}
            {temperature}
          </div>
        </div>
      </main>
    </div>
  );
}
